runtime: python39  # Python runtime environment

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app

instance_class: F2  # Specify the instance class (adjust based on needs)

env_variables:
  APP_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5

network:
  session_affinity: false

handlers:
  - url: /.*  # Catch-all URL handler for all other requests
    script: auto  # Automatically route to the FastAPI app
